# Generated by Django 2.2.9 on 2019-12-27 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Заголовок')),
                ('slug', models.SlugField(unique=True)),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('image', models.ImageField(help_text='700px-400px', upload_to='images/', verbose_name='Изображение')),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания записи')),
                ('date_update', models.DateTimeField(auto_now=True, verbose_name='Дата последнего изменения записи')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-date_create'],
            },
        ),
    ]
